name: Codacy Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '34 22 * * 5'
  workflow_dispatch: {}   # Allow manual triggering from the Actions tab

permissions:
  contents: read

jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read          # required for checkout
      security-events: write  # required to upload SARIF results
      actions: read           # required for SARIF upload in private repositories

    strategy:
      fail-fast: false
      matrix:
        tool: [ "shellcheck", "remark-lint", "yamllint", "psscriptanalyzer" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Detect if there are files relevant for the current tool.
      # If no files are found, we skip analysis to avoid "configuration error".
      - name: Detect target files (${{ matrix.tool }})
        id: detect
        shell: bash
        run: |
          shopt -s globstar nullglob
          TOOL="${{ matrix.tool }}"
          case "$TOOL" in
            shellcheck)
              FILES=( **/*.sh **/*.bash **/*.zsh )
              ;;
            remark-lint)
              FILES=( **/*.md )
              ;;
            yamllint)
              FILES=( **/*.yml **/*.yaml )
              ;;
            psscriptanalyzer)
              FILES=( **/*.ps1 )
              ;;
            *)
              echo "Unknown tool: $TOOL" >&2
              exit 1
              ;;
          esac

          # Filter: keep only existing files
          EXISTING=()
          for f in "${FILES[@]}"; do
            [[ -f "$f" ]] && EXISTING+=( "$f" )
          done

          if (( ${#EXISTING[@]} == 0 )); then
            echo "has_files=false" >> "$GITHUB_OUTPUT"
            echo "No matching files for tool '$TOOL'. Skipping analysis."
          else
            echo "has_files=true" >> "$GITHUB_OUTPUT"
            printf '%s\n' "${EXISTING[@]}" | sed 's/^/ - /'
          fi

      # Run Codacy CLI only if relevant files exist for this tool
      - name: Run Codacy Analysis CLI (${{ matrix.tool }})
        if: steps.detect.outputs.has_files == 'true'
        uses: codacy/codacy-analysis-cli-action@d840f886c4bd4edc059706d09c6a1586111c540b
        with:
          tool: ${{ matrix.tool }}
          # Keep the project token only if you are using Codacy SaaS.
          # Otherwise, you can safely remove this line.
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          format: sarif
          output: results-${{ matrix.tool }}.sarif
          gh-code-scanning-compat: true
          # Always generate SARIF regardless of issues count
          max-allowed-issues: 2147483647
          # Do not upload to Codacy SaaS here, only produce SARIF for GitHub
          upload: false

      # Upload SARIF results to GitHub Security tab
      - name: Upload SARIF (${{ matrix.tool }})
        if: steps.detect.outputs.has_files == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results-${{ matrix.tool }}.sarif
